import Link from 'next/link';
import Image from 'next/image';
import type { Metadata } from 'next';
import { products } from '@/data/products';
import ProductCard from '@/components/ProductCard';
export const metadata: Metadata = { title: 'Home', description: 'Lumora brings together thoughtful tech and everyday essentials for modern living.' };
export default function HomePage() {
  const featured = products.filter((p) => p.featured);
  return <main>
    <section className="overflow-hidden bg-slate-950 text-white"><div className="container-shell grid min-h-[620px] items-center gap-10 py-20 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-sm font-black uppercase tracking-[0.2em] text-violet-300">Curated technology · Everyday design</p><h1 className="mt-5 max-w-3xl text-5xl font-black leading-[0.95] tracking-tight sm:text-6xl">Better objects for the way you live.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">Meet a focused collection of headphones, wearables, desk essentials, and accessories that balance useful technology with quiet, intentional design.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/products" className="rounded-2xl bg-white px-6 py-3.5 text-sm font-black text-slate-950 hover:bg-violet-200">Shop the collection</Link><Link href="#featured" className="rounded-2xl border border-white/20 px-6 py-3.5 text-sm font-bold text-white hover:bg-white/10">See featured products</Link></div><div className="mt-10 flex flex-wrap gap-8 text-sm text-slate-400"><span>✓ Free shipping over ₹20,000</span><span>✓ 2-year selected warranty</span><span>✓ Guest checkout</span></div></div><div className="relative mx-auto w-full max-w-xl"><div className="absolute -left-6 -top-6 h-36 w-36 rounded-full bg-violet-500/30 blur-3xl" /><div className="absolute -bottom-10 -right-8 h-48 w-48 rounded-full bg-cyan-400/20 blur-3xl" /><div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-white/5 p-4 shadow-2xl"><Image src="/products/airwave.svg" alt="AirWave Pro headphones" width={760} height={570} priority className="w-full rounded-[1.5rem]" /><div className="flex items-center justify-between gap-4 p-4"><div><p className="text-xs uppercase tracking-wider text-slate-400">Featured pick</p><p className="mt-1 text-lg font-bold">AirWave Pro</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">₹14,999</span></div></div></div></div></section>
    <section id="featured" className="container-shell py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Handpicked collection</p><h2 className="mt-2 text-3xl font-black tracking-tight">Featured products</h2><p className="mt-2 max-w-xl text-slate-500">A tight selection of customer favorites and new arrivals.</p></div><Link href="/products" className="font-bold text-violet-600 hover:underline">View all products →</Link></div><div className="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{featured.map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
    <section className="container-shell pb-20"><div className="grid gap-5 md:grid-cols-3"><div className="rounded-3xl bg-violet-100 p-7"><p className="text-3xl">✦</p><h2 className="mt-8 text-xl font-black">Designed to last</h2><p className="mt-2 text-sm leading-6 text-slate-600">Thoughtful details, durable materials, and practical specifications.</p></div><div className="rounded-3xl bg-slate-900 p-7 text-white"><p className="text-3xl">◌</p><h2 className="mt-8 text-xl font-black">Easy from the start</h2><p className="mt-2 text-sm leading-6 text-slate-300">Browse as a guest, save a cart locally, and sign in only when you want to.</p></div><div className="rounded-3xl bg-cyan-100 p-7"><p className="text-3xl">↗</p><h2 className="mt-8 text-xl font-black">Made for modern work</h2><p className="mt-2 text-sm leading-6 text-slate-600">From focused desks to full-day listening, every item has a clear use case.</p></div></div></section>
  </main>;
}
